imports:
  - { resource: ./apps/application.yaml }
  - { resource: ./Appointments/application.yaml }
  - { resource: ./Users/application.yaml }
  - { resource: ./workspaces/application.yaml }
  - { resource: ./Shared/application.yaml }
