version: '3.8'

services:

  calendar-backend:
    build: .
    command: bash -c "npm run build && npm run start:calendar:backend"
    depends_on:
      - "rabbitmq"
    ports:
      - 3000:3000
    volumes:
      - .:/code:delegated

  frontend:
    build: ./src/apps/calendar/frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /usr/src/app/node_modules
      - ./src/apps/calendar/frontend:/usr/src/app
    ports:
      - 2000:2000  

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  node_modules:
