version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  depends_on:
    - rabbitmq
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  calendar-app:
    build: ./src/apps/calendar/frontend
    depends_on:
      - calendar-backend
    ports:
      - 3000:3000

  calendar-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:calendar:backend"
    ports:
      - 5000:5000

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  node_modules:
  esdata:
    driver: local
