version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  #calendar-backend:
     #<<: *default-app
    #command: bash -c "npm run build && npm run start:calendar:backend"
    #ports:
      #- 3000:3000

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  node_modules:
  esdata:
    driver: local
